
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T14:21:36-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a4c6509c9b76b6174c4c38611ff78e530204b6e",
 "version": "0+untagged.26.g4a4c650"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
