
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-22T12:51:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "423583337072f6442a5a5928a45168fc89b6791a",
 "version": "0+untagged.23.g4235833"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
