
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-22T13:11:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "adf6102baa7094e2ddaf391d3820df51de920029",
 "version": "0+untagged.25.gadf6102"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
